[project]
name = "python-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium>=1.2.2",
    "numpy>=2.3.4",
    "onnxscript>=0.5.6",
    "requests>=2.32.5",
    "stable-baselines3[extra]>=2.7.0",
]
